title: SimonChen
logo: /assets/img/selfie.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics
theme: jekyll-theme-minimal
search : true
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
