title: SimonChen
logo: /assets/img/selfie.jpg
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics
# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
# remote_theme: yaoyao-liu/minimal-light
search : true
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# font: "Serif"

header_links:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
