# 网站基本信息
title: Your Name
description: Your personal website.
logo: /assets/img/selfie.jpg # 替换为你的个人头像路径

# 使用 Minimal Light 主题
remote_theme: yaoyao-liu/minimal-light
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# 搜索功能
search: true

# 主题皮肤设置
minimal_light_skin: "dark" # 可选: default, dark, solarized-dark, etc.

# 主页左侧个人信息
author:
  name: Your Name
  title: Ph.D. Student
  affiliation: Your Affiliation
  email: yourname@example.com
  scholar: https://scholar.google.com/citations?user=YOUR_ID
  github: https://github.com/yourgithub
  linkedin: https://linkedin.com/in/yourlinkedin
  cv: /files/Your_CV.pdf # 替换为你的 CV 链接

# 导航栏
header:
  navigation:
    - title: "Home"
      url: /
    - title: "Publications"
      url: /publications/
    - title: "About"
      url: /about/

# 页脚
footer:
  links:
    - title: "GitHub"
      url: https://github.com/yourgithub
    - title: "Google Scholar"
      url: https://scholar.google.com/citations?user=YOUR_ID
    - title: "LinkedIn"
      url: https://linkedin.com/in/yourlinkedin